### ISSUE TITLE
Sketch material not showing up in the sketch packs 

### ISSUE THREAD

**Issue by websiddu** [sketchpacks/bug-reports#38] opened 2017-07-19 03:10 UTC
I'm really not sure what I'm doing wrong, 

https://github.com/websiddu/sketch-material won't show up in the sketch packs list.

**Comment by willdavis** [comment] 2017-07-20 21:53
@websiddu thanks for pointing this out.  After looking through the logs, the problem is on our end.

There was a bug in Sketchpacks Relay that was causing the plugin to fail to insert into the registry.  However, Relay was correctly integrated with the repository and is firing webhooks.  Those webhooks were not being processed because the record was missing from the DB.

I've pushed a fix for this and manually refreshed sketch-material. So nothing else you need to do.
When you push changes, you can check them at the plugins endpoint to be sure they worked.
```
https://api.sketchpacks.com/v1/plugins/com.websiddu.sketch.material
```

We are working on a dashboard for plugin developers, which will expose this info as well as error messages when things don't work.

**Closed as completed by willdavis** 2017-07-20 21:53 UTC

**Comment by websiddu** [comment] 2017-07-20 23:55
Thanks 👍 I can see the plugin.
